name: ci

on:
  pull_request:
    paths:
      - "backend/**"
      - "web/**"
      - "supabase/**"
      - ".github/workflows/ci.yml"
  workflow_dispatch:

jobs:
  backend:
    name: Backend - lint & tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Lint & type-check
        run: |
          ruff check .
          black --check .
          mypy .

      - name: Tests
        run: pytest -q

  web:
    name: Web - lint, type-check & tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: web/package.json

      - name: Install deps
        run: npm ci

      - name: Validate Supabase secrets
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          if [ -z "$SUPABASE_URL" ]; then
            echo "::error::SUPABASE_URL secret is not set"
            exit 1
          fi
          if [ -z "$SUPABASE_ANON_KEY" ]; then
            echo "::error::SUPABASE_ANON_KEY secret is not set"
            exit 1
          fi
          echo "✅ Supabase secrets are available"

      - name: Lint
        run: npm run lint

      - name: Type check
        run: npm run build -- --mode=ci

      - name: Tests
        run: npm run test

      - name: Build with Supabase env
        env:
          VITE_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          echo "Building with Supabase URL: ${VITE_SUPABASE_URL:0:20}..."
          npm run build

  lighthouse:
    name: Lighthouse Performance Check
    runs-on: ubuntu-latest
    needs: web
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: web/package.json

      - name: Install deps
        run: npm ci
        working-directory: web

      - name: Build app
        env:
          VITE_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: npm run build
        working-directory: web

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli@0.12.x

      - name: Run Lighthouse CI
        run: |
          lhci autorun --upload.target=temporary-public-storage
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        working-directory: web