name: Test Web App with Secrets

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "web/**"

jobs:
  test-web:
    name: Test Web App with Supabase Secrets
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: web/package.json

      - name: Install deps
        run: npm ci

      - name: Validate Supabase secrets
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          if [ -z "$SUPABASE_URL" ]; then
            echo "::error::SUPABASE_URL secret is not set"
            exit 1
          fi
          if [ -z "$SUPABASE_ANON_KEY" ]; then
            echo "::error::SUPABASE_ANON_KEY secret is not set"
            exit 1
          fi
          echo "✅ Supabase secrets are available"

      - name: Build web app with secrets
        env:
          VITE_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          echo "Building with Supabase URL: ${VITE_SUPABASE_URL:0:20}..."
          npm run build

      - name: Test build output
        run: |
          if [ -d "dist" ]; then
            echo "✅ Build successful - dist folder created"
            ls -la dist/
          else
            echo "❌ Build failed - no dist folder"
            exit 1
          fi
